### ISSUE TITLE
Change SASS for classic CSS

### ISSUE THREAD

**Issue by ematipico** [biomejs/website#706]
We don't need SASS now that the majority of [the browsers support CSS nesting](https://caniuse.com/?search=css%20nesting).

**Comment by mochi-sann** [comment]
I'm working on the work described in that Issue right now, like the file at this link 
https://github.com/biomejs/website/pull/1203/files#diff-da27d798d2b0283a7abb796fbf9a588f5ed817ce08efb4edd7aaaac29029dc7dR1-R23
 
I have a file that is written in scss proprietary notation, do you want to change this so that it can be expressed in naitive css?
